name: Backend-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "BillChopBE/**"

jobs:
  build-backend:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./BillChopBE
    strategy:
      matrix:
        # Testing needs to happen on multiple platforms, since our developers use a variety of machines
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ["5.0.100"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build solution
        run: dotnet build
      - name: Test solution
        run: dotnet test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: ./BillChopBE/BillChopBE/bin
      - name: Clean solution
        run: dotnet clean
      - name: SonarScanner for .NET 5 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # The key of the SonarQube project
          sonarProjectKey: ainoraz-billchop-fe
          # The name of the SonarQube project
          sonarProjectName: ainoraz-billchop-fe
          # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: ainoraz
          dotnetBuildArguments: ./BillChopBE
          dotnetDisableTests: true
        if: matrix.os == 'ubuntu-latest'