name: Backend-CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "BillChopBE/**"
      - .github/workflows/backend.yml

jobs:
  build-backend:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./BillChopBE
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ["5.0.x"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build solution
        run: dotnet build
      - name: Test solution
        run: dotnet test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-build
          path: ./BillChopBE/BillChopBE/bin
      - name: Clean solution
        run: dotnet clean

  be-code-quality:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./BillChopBE
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ["5.0.x"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: SonarScanner for .NET 5 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          sonarProjectKey: ainoraz-BillChopBE
          sonarProjectName: ainoraz-BillChopBE
          sonarOrganization: ainoraz
          dotnetBuildArguments: ./BillChopBE
          dotnetDisableTests: true
        if: matrix.os == 'ubuntu-latest'